director_uuid: 93c01d2d-a2a5-49d8-8d02-389fd223a9cf

name: consul

jobs:
- instances: 3
  name: consul_z1
  networks:
  - name: consul1
    static_ips:
    - 10.244.4.4
    - 10.244.4.5
    - 10.244.4.6
  resource_pool: consul_z1
  templates:
  - name: consul_agent
    release: consul
  persistent_disk: 1024
  properties:
    consul:
      agent:
        mode: server

networks:
- name: consul1
  subnets:
  - cloud_properties:
      name: random
    gateway: 10.244.4.1
    range: 10.244.4.0/24
    reserved:
    - 10.244.4.2-10.244.4.3
    - 10.244.4.12-10.244.4.254
    static:
    - 10.244.4.4
    - 10.244.4.5
    - 10.244.4.6
    - 10.244.4.7
    - 10.244.4.8
  type: manual

compilation:
  cloud_properties: {}
  network: consul1
  reuse_compilation_vms: true
  workers: 3

releases:
- name: consul
  version: latest

resource_pools:
- cloud_properties: {}
  name: consul_z1
  network: consul1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000

properties:
  consul:
    agent:
      domain: cf.internal
      servers:
        lan:
          - 10.244.4.4
          - 10.244.4.5
          - 10.244.4.6
    agent_cert: ''
    agent_key: ''
    ca_cert: ''
    encrypt_keys: []
    require_ssl: false
    server_cert: ''
    server_key: ''
